# Generated by Django 4.1.3 on 2022-12-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_tag_options_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
