# Generated by Django 4.1.3 on 2022-12-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_directory_path', verbose_name='Picture'),
        ),
    ]
